### ISSUE TITLE
Set up a GitBook account

### ISSUE THREAD

**Issue by BrandonHarrisonCode** [hrfofut/idb#10]

**Comment by BrandonHarrisonCode** [comment]
I think it has to be under your ID Harrison

**Comment by hrfofut** [comment]
Things are made, need to be written. Link at:
[ https://hrfofut.gitbooks.io/report/ ](https://hrfofut.gitbooks.io/report/ )
[ https://hrfofut.gitbooks.io/api/ ](https://hrfofut.gitbooks.io/api/)
