### ISSUE TITLE
User Story 14: Gyms category filter

### ISSUE THREAD

**Issue by cindyqtruong** [hrfofut/idb#100]
As a user who is specifically interested in yoga, I want to be able to look for local yoga places.

Assumptions:
- implemented gyms filter by category
- implemented global search that would return results for a search like "yoga"

Time Estimate: 3 hours

**Comment by fantomats15** [comment]
Well we don't have the category function for gyms right now but that will be work on in the future.

**Comment by cindyqtruong** [comment]
It is possible to search for terms like "yoga" right now though! For that at least, Actual Time: 6 hours
