### ISSUE TITLE
Users should be able to see what workouts are available in English

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#112]
Some of the workouts are in German, and it makes it impossible to decipher what exercise it is without leaving the website and searching. 

Estimate: 1 Day

Assumption: 
-No further exercises are added to the website
-Some available translation service is used

Adjustment: 1 Day

**Comment by cindyqtruong** [comment]
I believe all of the workouts are in English now? This used to be a known issue, but I think it's been fixed after an API switch.

**Comment by rebekkahkoo** [comment]
looks good! thanks :)

**Comment by dav-s** [comment]
http://caloriekiller.club/workouts/11767

**Comment by hrfofut** [comment]
Truch is not foreign language, it is a misspelling by the original creators of the data.

**Comment by hrfofut** [comment]
Actual Time: 1 Day
