### ISSUE TITLE
Users should be able to visit the about page to read about the developers of the website

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#114]
The about page is broken and inaccessible. 

Estimate: 1 Day

Assumptions:
-The About Page is probably broken because I started creating issues and the way you're pulling Github info is causing errors

Adjustment: 1 Day

**Comment by cindyqtruong** [comment]
Fixed by checking authors of issues before attempting to increment issue count.

Actual time: 0.5 hour
