### ISSUE TITLE
Users should not see multiple of the same workouts

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#115]
There are workouts that are listed multiple times.

Estimate: 2 Days

Assumptions: 
-Use a SQL query to prevent duplicate data from being entered into the database
-Use a SQL query to clear duplicates from the database

Adjustment: 3 Days

**Comment by cindyqtruong** [comment]
Technically the workouts with duplicate names were different workouts (e.g., running at 5mph vs. running at 20 mph), but to avoid confusion, we've just gone ahead and removed workouts with duplicate names.

Actual time: 2 days
