### ISSUE TITLE
Users should be able to see how much of one serving size something is.

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#116]
Serving sizes are displayed but it does not state what unit of measurement they are in. 

Estimate: 1 Day

Assumption:
-API that you are using has accurate information about the serving size of the food you are displaying. 

Adjusted: 1.5 Days

**Comment by ewk298** [comment]
Developers added gram units to serving size, thanks!

**Comment by hrfofut** [comment]
Finished, actual time: 1 hour
