### ISSUE TITLE
Users should be to see the prices of the gyms they are viewing. 

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#117]
When the details page for a gym is being viewed, price says "N/A"

Estimate: 2 Days

Assumption:
-The API you are using has the price of a gym memberrship
-Or you can get rid of this 

Adjusted: 2.5 Days

**Comment by cindyqtruong** [comment]
It seems like most gyms don't actually have price levels, so it might be best to just not include it.

**Comment by cindyqtruong** [comment]
We've decided to get rid of it entirely, since it's not useful for most gyms. 

Actual time: 2 Days
