### ISSUE TITLE
Users should know what the labels on the website mean, or have a place to reference what labels mean.

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#118]
On the exercise page there are labels such as "met" with numbers associated with them, but I have no idea what it means.

Estimate: 0.5 Days

Assumption:
-Just put something in your about page real quick about what stuff on your website means 
-Don't assume the user knows what you mean

Adjusted: 1 Day

**Comment by cindyqtruong** [comment]
We're considering adding a tooltip to the workout detail pages explaining what MET means.

**Comment by cindyqtruong** [comment]
For the sake of mobile friendliness, we've just added a plaintext description of MET to the workout detail page. 

Actual time: 0.5 hour
