### ISSUE TITLE
Users should be able to access the food filter menu easily and see it in its entirety. 

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#120]
The food filter menu currently goes off screen and it is hard to access all the options available. 

Estimate: 2 Days

Assumptions:
-Restructure the food filter menu by reorganizing what you are sorting by
-May have to decrease the number of categories being sorted 
-May require changes to database

Adjustment: 3 Days

**Comment by cindyqtruong** [comment]
This has been fixed by making the drop-down menus scrollable. It should work on mobile, but that still needs to be checked. 

Adjusted time: 1 hour
