### ISSUE TITLE
Users should be able to see how foods, exercises, and gyms are related to each other.

### ISSUE THREAD

**Issue by TimCoding** [hrfofut/idb#121]
Currently the food, exercise, and gym detail pages do not point to specific instances. They just point to the overall models page. 

Estimate: 4 Day

Assumptions:
-Already have an idea of how these pages should link to specific instances 
-Database is organized in a way where linking these specific instances together is logical

Adjusted: 2 Days

**Comment by hrfofut** [comment]
User should now be able to analyze the linkage between all instances of food, exercises, gyms, and stores. Data collation has been improved tremendously. 

Actual time: 2 Days
