### ISSUE TITLE
User Story 9: Food browsing

### ISSUE THREAD

**Issue by cindyqtruong** [hrfofut/idb#81]
As a foodie looking to discover new foods to eat, I want to be able to easily browse pictures of food and see a brief overview of nutritional info.

Assumptions:
- can easily navigate the food grid page
- each food card displays brief overview of nutritional info without having to navigate to that food item page

Time Estimate: 4 hours

**Comment by fantomats15** [comment]
This is done

**Comment by cindyqtruong** [comment]
Actual Time: 4 hours

We now also show more nutritional info than before on the food grid page.
