### ISSUE TITLE
User Story 11: Gym ratings sort

### ISSUE THREAD

**Issue by cindyqtruong** [hrfofut/idb#96]
As someone looking to get into weightlifting, I want to sort gyms by rating in order to see what gyms in my area have the highest ratings.

Assumptions:
- implemented sorting by rating for gyms
- can easily sort from gym grid page

Time Estimate: 4 hours

**Comment by fantomats15** [comment]
Sorting by ratings along with others attribute is added to gyms. 
Actual time: 3 hours
