### ISSUE TITLE
User Story 12: Calorie and fat food sort

### ISSUE THREAD

**Issue by cindyqtruong** [hrfofut/idb#97]
As someone on a diet planning my next meal, I want to be able to see what foods have the lowest calorie count and fat content.

Assumption
- implemented sorting by calories for food
- implemented sorting by fat for food
- can easily accessed sort options from food grid page

Time Estimate: 4 hours

**Comment by fantomats15** [comment]
User can now sort food by name, calories, fat, protein, and other attributes.
Actual time: 3 hours
