### ISSUE TITLE
User Story 13: Shopping on a budget

### ISSUE THREAD

**Issue by cindyqtruong** [hrfofut/idb#99]
As a user on a budget, I want to sort grocery stores near me by price level so that I can see which grocery stores are cheapest.

Assumptions:
- implemented grocery store sort by price level
- alternatively, implemented grocery store filter by (low) price level

Time Estimate: 3 hours

**Comment by fantomats15** [comment]
User can now sort grocery store base on price level.
Actual time: 3 hours
